# Generated by Django 5.1.7 on 2025-04-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans_done', to=settings.AUTH_USER_MODEL)),
                ('scanned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
